//! PLY saver: serialises a `solid_rs::Scene` to ASCII or binary-LE PLY.

use std::io::Write;

use glam::{Vec2, Vec3, Vec4};
use solid_rs::prelude::*;
use solid_rs::scene::Scene;
use solid_rs::{Result, SolidError};

use crate::PLY_FORMAT;

/// Saves a [`Scene`] as a Stanford PLY file.
///
/// The default [`Saver::save`] writes **ASCII PLY 1.0**.  For compact
/// little-endian binary output call [`PlySaver::save_binary_le`] directly.
pub struct PlySaver;

impl Saver for PlySaver {
    fn format_info(&self) -> &FormatInfo {
        &PLY_FORMAT
    }

    fn save(&self, scene: &Scene, writer: &mut dyn Write, options: &SaveOptions) -> Result<()> {
        write_ascii(scene, writer, options)
    }
}

impl PlySaver {
    /// Write binary little-endian PLY to `writer`.
    pub fn save_binary_le(
        scene:   &Scene,
        writer:  &mut dyn Write,
        options: &SaveOptions,
    ) -> Result<()> {
        write_binary_le(scene, writer, options)
    }
}

// ── Shared geometry collection ────────────────────────────────────────────────

struct PlyGeom<'a> {
    vertices:   Vec<&'a Vertex>,
    indices:    Vec<u32>,
    has_normals: bool,
    has_uvs:     bool,
    has_colors:  bool,
}

fn collect_geometry(scene: &Scene) -> PlyGeom<'_> {
    let mut vertices: Vec<&Vertex> = Vec::new();
    let mut indices:  Vec<u32>     = Vec::new();

    for mesh in &scene.meshes {
        let base = vertices.len() as u32;
        vertices.extend(mesh.vertices.iter());
        for prim in &mesh.primitives {
            if prim.topology == Topology::TriangleList {
                for &idx in &prim.indices {
                    indices.push(idx + base);
                }
            }
        }
    }

    let has_normals = vertices.iter().any(|v| v.normal.is_some());
    let has_uvs     = vertices.iter().any(|v| v.uvs[0].is_some());
    let has_colors  = vertices.iter().any(|v| v.colors[0].is_some());

    PlyGeom { vertices, indices, has_normals, has_uvs, has_colors }
}

fn build_header(geom: &PlyGeom<'_>, format_line: &str, options: &SaveOptions) -> String {
    let mut h = String::with_capacity(512);
    h.push_str("ply\n");
    h.push_str(format_line);
    h.push('\n');

    let gen = options.generator.as_deref().unwrap_or("solid-ply (SolidRS)");
    h.push_str(&format!("comment Generated by {gen}\n"));
    if let Some(copyright) = &options.copyright {
        h.push_str(&format!("comment Copyright: {copyright}\n"));
    }

    h.push_str(&format!("element vertex {}\n", geom.vertices.len()));
    h.push_str("property float x\n");
    h.push_str("property float y\n");
    h.push_str("property float z\n");
    if geom.has_normals {
        h.push_str("property float nx\n");
        h.push_str("property float ny\n");
        h.push_str("property float nz\n");
    }
    if geom.has_uvs {
        h.push_str("property float s\n");
        h.push_str("property float t\n");
    }
    if geom.has_colors {
        h.push_str("property uchar red\n");
        h.push_str("property uchar green\n");
        h.push_str("property uchar blue\n");
        h.push_str("property uchar alpha\n");
    }

    let n_faces = geom.indices.len() / 3;
    h.push_str(&format!("element face {n_faces}\n"));
    h.push_str("property list uchar uint vertex_indices\n");
    h.push_str("end_header\n");
    h
}

// ── ASCII writer ──────────────────────────────────────────────────────────────

fn write_ascii(scene: &Scene, w: &mut dyn Write, options: &SaveOptions) -> Result<()> {
    let geom = collect_geometry(scene);
    let header = build_header(&geom, "format ascii 1.0", options);
    w.write_all(header.as_bytes()).map_err(SolidError::Io)?;

    for v in &geom.vertices {
        let p = v.position;
        write!(w, "{} {} {}", p.x, p.y, p.z).map_err(SolidError::Io)?;

        if geom.has_normals {
            let n = v.normal.unwrap_or(Vec3::Y);
            write!(w, " {} {} {}", n.x, n.y, n.z).map_err(SolidError::Io)?;
        }
        if geom.has_uvs {
            let uv = v.uvs[0].unwrap_or(Vec2::ZERO);
            let t  = if options.flip_uv_v { 1.0 - uv.y } else { uv.y };
            write!(w, " {} {}", uv.x, t).map_err(SolidError::Io)?;
        }
        if geom.has_colors {
            let c = vertex_color_bytes(v);
            write!(w, " {} {} {} {}", c[0], c[1], c[2], c[3]).map_err(SolidError::Io)?;
        }
        writeln!(w).map_err(SolidError::Io)?;
    }

    for tri in geom.indices.chunks(3) {
        writeln!(w, "3 {} {} {}", tri[0], tri[1], tri[2]).map_err(SolidError::Io)?;
    }

    Ok(())
}

// ── Binary LE writer ──────────────────────────────────────────────────────────

fn write_binary_le(scene: &Scene, w: &mut dyn Write, options: &SaveOptions) -> Result<()> {
    let geom = collect_geometry(scene);
    let header = build_header(&geom, "format binary_little_endian 1.0", options);
    w.write_all(header.as_bytes()).map_err(SolidError::Io)?;

    for v in &geom.vertices {
        let p = v.position;
        w.write_all(&p.x.to_le_bytes()).map_err(SolidError::Io)?;
        w.write_all(&p.y.to_le_bytes()).map_err(SolidError::Io)?;
        w.write_all(&p.z.to_le_bytes()).map_err(SolidError::Io)?;

        if geom.has_normals {
            let n = v.normal.unwrap_or(Vec3::Y);
            w.write_all(&n.x.to_le_bytes()).map_err(SolidError::Io)?;
            w.write_all(&n.y.to_le_bytes()).map_err(SolidError::Io)?;
            w.write_all(&n.z.to_le_bytes()).map_err(SolidError::Io)?;
        }
        if geom.has_uvs {
            let uv = v.uvs[0].unwrap_or(Vec2::ZERO);
            let t  = if options.flip_uv_v { 1.0_f32 - uv.y } else { uv.y };
            w.write_all(&uv.x.to_le_bytes()).map_err(SolidError::Io)?;
            w.write_all(&t.to_le_bytes()).map_err(SolidError::Io)?;
        }
        if geom.has_colors {
            let c = vertex_color_bytes(v);
            w.write_all(&c).map_err(SolidError::Io)?;
        }
    }

    for tri in geom.indices.chunks(3) {
        w.write_all(&[3u8]).map_err(SolidError::Io)?;
        for &idx in tri {
            w.write_all(&idx.to_le_bytes()).map_err(SolidError::Io)?;
        }
    }

    Ok(())
}

// ── Helper ────────────────────────────────────────────────────────────────────

fn vertex_color_bytes(v: &Vertex) -> [u8; 4] {
    let c = v.colors[0].unwrap_or(Vec4::ONE);
    [
        (c.x.clamp(0.0, 1.0) * 255.0) as u8,
        (c.y.clamp(0.0, 1.0) * 255.0) as u8,
        (c.z.clamp(0.0, 1.0) * 255.0) as u8,
        (c.w.clamp(0.0, 1.0) * 255.0) as u8,
    ]
}
