//! PLY saver: serialises a `solid_rs::Scene` to ASCII or binary PLY.

use std::io::Write;

use glam::{Vec2, Vec3, Vec4};
use solid_rs::prelude::*;
use solid_rs::scene::Scene;
use solid_rs::{Result, SolidError};

use crate::PLY_FORMAT;

/// Saves a [`Scene`] as a Stanford PLY file.
///
/// The default [`Saver::save`] writes **ASCII PLY 1.0**.  For compact binary
/// output call [`PlySaver::save_binary_le`], [`PlySaver::save_binary_be`], or
/// [`PlySaver::save_with_precision`] directly.
pub struct PlySaver;

impl Saver for PlySaver {
    fn format_info(&self) -> &FormatInfo {
        &PLY_FORMAT
    }

    fn save(&self, scene: &Scene, writer: &mut dyn Write, options: &SaveOptions) -> Result<()> {
        write_ascii(scene, writer, options, false)
    }
}

impl PlySaver {
    /// Write binary little-endian PLY to `writer`.
    pub fn save_binary_le(
        scene:   &Scene,
        writer:  &mut dyn Write,
        options: &SaveOptions,
    ) -> Result<()> {
        write_binary(scene, writer, options, false, false)
    }

    /// Write binary big-endian PLY to `writer`.
    pub fn save_binary_be(
        scene:   &Scene,
        writer:  &mut dyn Write,
        options: &SaveOptions,
    ) -> Result<()> {
        write_binary(scene, writer, options, true, false)
    }

    /// Write binary little-endian PLY with selectable floating-point precision.
    ///
    /// When `use_double` is `true`, positions, normals, and tangents are written
    /// as `double` (`f64`); otherwise they are written as `float` (`f32`).
    pub fn save_with_precision(
        scene:      &Scene,
        writer:     &mut dyn Write,
        use_double: bool,
    ) -> Result<()> {
        write_binary(scene, writer, &SaveOptions::default(), false, use_double)
    }
}

// ── Shared geometry collection ────────────────────────────────────────────────

struct PlyGeom<'a> {
    vertices:     Vec<&'a Vertex>,
    indices:      Vec<u32>,
    has_normals:  bool,
    has_tangents: bool,
    /// One entry per UV channel (0–7); `true` iff any vertex has that channel set.
    has_uvs:      [bool; 8],
    has_colors:   bool,
}

fn collect_geometry(scene: &Scene) -> PlyGeom<'_> {
    let mut vertices: Vec<&Vertex> = Vec::new();
    let mut indices:  Vec<u32>     = Vec::new();

    for mesh in &scene.meshes {
        let base = vertices.len() as u32;
        vertices.extend(mesh.vertices.iter());
        for prim in &mesh.primitives {
            if prim.topology == Topology::TriangleList {
                for &idx in &prim.indices {
                    indices.push(idx + base);
                }
            }
        }
    }

    let has_normals  = vertices.iter().any(|v| v.normal.is_some());
    let has_tangents = vertices.iter().any(|v| v.tangent.is_some());
    let has_colors   = vertices.iter().any(|v| v.colors[0].is_some());

    let mut has_uvs = [false; 8];
    for ch in 0..8 {
        has_uvs[ch] = vertices.iter().any(|v| v.uvs[ch].is_some());
    }

    PlyGeom { vertices, indices, has_normals, has_tangents, has_uvs, has_colors }
}

/// Returns the canonical PLY property name pair `(s_name, t_name)` for a UV channel.
fn uv_channel_names(ch: usize) -> (&'static str, &'static str) {
    match ch {
        0 => ("s",  "t"),
        1 => ("s1", "t1"),
        2 => ("s2", "t2"),
        3 => ("s3", "t3"),
        4 => ("s4", "t4"),
        5 => ("s5", "t5"),
        6 => ("s6", "t6"),
        _ => ("s7", "t7"),
    }
}

fn build_header(
    geom:        &PlyGeom<'_>,
    format_line: &str,
    options:     &SaveOptions,
    use_double:  bool,
) -> String {
    let ft = if use_double { "double" } else { "float" };
    let mut h = String::with_capacity(512);
    h.push_str("ply\n");
    h.push_str(format_line);
    h.push('\n');

    let gen = options.generator.as_deref().unwrap_or("solid-ply (SolidRS)");
    h.push_str(&format!("comment Generated by {gen}\n"));
    if let Some(copyright) = &options.copyright {
        h.push_str(&format!("comment Copyright: {copyright}\n"));
    }

    h.push_str(&format!("element vertex {}\n", geom.vertices.len()));
    h.push_str(&format!("property {ft} x\n"));
    h.push_str(&format!("property {ft} y\n"));
    h.push_str(&format!("property {ft} z\n"));
    if geom.has_normals {
        h.push_str(&format!("property {ft} nx\n"));
        h.push_str(&format!("property {ft} ny\n"));
        h.push_str(&format!("property {ft} nz\n"));
    }
    if geom.has_tangents {
        h.push_str(&format!("property {ft} tx\n"));
        h.push_str(&format!("property {ft} ty\n"));
        h.push_str(&format!("property {ft} tz\n"));
        h.push_str(&format!("property {ft} tw\n"));
    }
    // Write one pair of UV properties per active channel.
    for ch in 0..8usize {
        if geom.has_uvs[ch] {
            let (s_name, t_name) = uv_channel_names(ch);
            h.push_str(&format!("property float {s_name}\n"));
            h.push_str(&format!("property float {t_name}\n"));
        }
    }
    if geom.has_colors {
        h.push_str("property uchar red\n");
        h.push_str("property uchar green\n");
        h.push_str("property uchar blue\n");
        h.push_str("property uchar alpha\n");
    }

    // Only write the face element when there are actual triangles (point-cloud support).
    let n_faces = geom.indices.len() / 3;
    if n_faces > 0 {
        h.push_str(&format!("element face {n_faces}\n"));
        h.push_str("property list uchar uint vertex_indices\n");
    }
    h.push_str("end_header\n");
    h
}

// ── ASCII writer ──────────────────────────────────────────────────────────────

fn write_ascii(
    scene:      &Scene,
    w:          &mut dyn Write,
    options:    &SaveOptions,
    use_double: bool,
) -> Result<()> {
    let geom   = collect_geometry(scene);
    let header = build_header(&geom, "format ascii 1.0", options, use_double);
    w.write_all(header.as_bytes()).map_err(SolidError::Io)?;

    for v in &geom.vertices {
        let p = v.position;
        if use_double {
            write!(w, "{} {} {}", p.x as f64, p.y as f64, p.z as f64)
                .map_err(SolidError::Io)?;
        } else {
            write!(w, "{} {} {}", p.x, p.y, p.z).map_err(SolidError::Io)?;
        }

        if geom.has_normals {
            let n = v.normal.unwrap_or(Vec3::Y);
            if use_double {
                write!(w, " {} {} {}", n.x as f64, n.y as f64, n.z as f64)
                    .map_err(SolidError::Io)?;
            } else {
                write!(w, " {} {} {}", n.x, n.y, n.z).map_err(SolidError::Io)?;
            }
        }
        if geom.has_tangents {
            let t = v.tangent.unwrap_or(Vec4::new(1.0, 0.0, 0.0, 1.0));
            if use_double {
                write!(w, " {} {} {} {}", t.x as f64, t.y as f64, t.z as f64, t.w as f64)
                    .map_err(SolidError::Io)?;
            } else {
                write!(w, " {} {} {} {}", t.x, t.y, t.z, t.w).map_err(SolidError::Io)?;
            }
        }
        for ch in 0..8usize {
            if geom.has_uvs[ch] {
                let uv = v.uvs[ch].unwrap_or(Vec2::ZERO);
                let tv = if options.flip_uv_v { 1.0_f32 - uv.y } else { uv.y };
                write!(w, " {} {}", uv.x, tv).map_err(SolidError::Io)?;
            }
        }
        if geom.has_colors {
            let c = vertex_color_bytes(v);
            write!(w, " {} {} {} {}", c[0], c[1], c[2], c[3]).map_err(SolidError::Io)?;
        }
        writeln!(w).map_err(SolidError::Io)?;
    }

    // Point-cloud scenes have no faces — omit the face section entirely.
    if !geom.indices.is_empty() {
        for tri in geom.indices.chunks(3) {
            writeln!(w, "3 {} {} {}", tri[0], tri[1], tri[2]).map_err(SolidError::Io)?;
        }
    }

    Ok(())
}

// ── Binary writer (LE and BE, float and double) ───────────────────────────────

fn write_binary(
    scene:      &Scene,
    w:          &mut dyn Write,
    options:    &SaveOptions,
    big_endian: bool,
    use_double: bool,
) -> Result<()> {
    let geom = collect_geometry(scene);
    let format_line = if big_endian {
        "format binary_big_endian 1.0"
    } else {
        "format binary_little_endian 1.0"
    };
    let header = build_header(&geom, format_line, options, use_double);
    w.write_all(header.as_bytes()).map_err(SolidError::Io)?;

    for v in &geom.vertices {
        let p = v.position;
        write_float(w, p.x, big_endian, use_double)?;
        write_float(w, p.y, big_endian, use_double)?;
        write_float(w, p.z, big_endian, use_double)?;

        if geom.has_normals {
            let n = v.normal.unwrap_or(Vec3::Y);
            write_float(w, n.x, big_endian, use_double)?;
            write_float(w, n.y, big_endian, use_double)?;
            write_float(w, n.z, big_endian, use_double)?;
        }
        if geom.has_tangents {
            let t = v.tangent.unwrap_or(Vec4::new(1.0, 0.0, 0.0, 1.0));
            write_float(w, t.x, big_endian, use_double)?;
            write_float(w, t.y, big_endian, use_double)?;
            write_float(w, t.z, big_endian, use_double)?;
            write_float(w, t.w, big_endian, use_double)?;
        }
        // UVs are always stored as f32 regardless of use_double.
        for ch in 0..8usize {
            if geom.has_uvs[ch] {
                let uv = v.uvs[ch].unwrap_or(Vec2::ZERO);
                let tv = if options.flip_uv_v { 1.0_f32 - uv.y } else { uv.y };
                if big_endian {
                    w.write_all(&uv.x.to_be_bytes()).map_err(SolidError::Io)?;
                    w.write_all(&tv.to_be_bytes()).map_err(SolidError::Io)?;
                } else {
                    w.write_all(&uv.x.to_le_bytes()).map_err(SolidError::Io)?;
                    w.write_all(&tv.to_le_bytes()).map_err(SolidError::Io)?;
                }
            }
        }
        if geom.has_colors {
            let c = vertex_color_bytes(v);
            w.write_all(&c).map_err(SolidError::Io)?;
        }
    }

    // Point-cloud scenes have no faces — omit the face section entirely.
    if !geom.indices.is_empty() {
        for tri in geom.indices.chunks(3) {
            w.write_all(&[3u8]).map_err(SolidError::Io)?;
            for &idx in tri {
                if big_endian {
                    w.write_all(&idx.to_be_bytes()).map_err(SolidError::Io)?;
                } else {
                    w.write_all(&idx.to_le_bytes()).map_err(SolidError::Io)?;
                }
            }
        }
    }

    Ok(())
}

/// Write one `f32` value, optionally promoted to `f64`, in the requested byte order.
#[inline]
fn write_float(w: &mut dyn Write, val: f32, big_endian: bool, use_double: bool) -> Result<()> {
    if use_double {
        let d = val as f64;
        if big_endian {
            w.write_all(&d.to_be_bytes()).map_err(SolidError::Io)
        } else {
            w.write_all(&d.to_le_bytes()).map_err(SolidError::Io)
        }
    } else if big_endian {
        w.write_all(&val.to_be_bytes()).map_err(SolidError::Io)
    } else {
        w.write_all(&val.to_le_bytes()).map_err(SolidError::Io)
    }
}

// ── Helper ────────────────────────────────────────────────────────────────────

fn vertex_color_bytes(v: &Vertex) -> [u8; 4] {
    let c = v.colors[0].unwrap_or(Vec4::ONE);
    [
        (c.x.clamp(0.0, 1.0) * 255.0) as u8,
        (c.y.clamp(0.0, 1.0) * 255.0) as u8,
        (c.z.clamp(0.0, 1.0) * 255.0) as u8,
        (c.w.clamp(0.0, 1.0) * 255.0) as u8,
    ]
}
